[package]
name = "mystore"
version = "0.1.0"
authors = ["werner <werner_a_e@yahoo.es>"]
edition = "2018"

[dependencies]
actix = "0.8"
actix-web = "1.0.0-beta"
actix-cors = "0.1.0"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.1"
